### ISSUE TITLE
allow fetching historicalTrades older than last 1000 trades

### ISSUE THREAD

**Issue by great9** [Bitrue-exchange/bitrue-official-api-docs#1]
as the title says. currently if requested "fromId=0", only last 1000 trades will be returned, not trades from 0.

**Comment by ifcwlme** [comment]
Found the same issue.

**Comment by Yoruichi** [comment]
Only last trades to query for this API.
i got your problem, and we'll provide a new API to query old trades ASAP

**Comment by gkosmr** [comment]
Hi there. Having the same issue. Any progress on this one?
