### ISSUE TITLE
No Market Data Stream Available

### ISSUE THREAD

**Issue by tradesmart844** [Bitrue-exchange/bitrue-official-api-docs#19]
Hi,

In order to read real time depth prices using market data streams. But currently its unavailable. Can you please add this so I can track real time prices. It will help developers if you add sample user & market data stream connection examples using web socket in main page.

**Comment by francesco-adamo** [comment]
I second this request, websocket streams for real time prices and real time orderbook data would be really useful!
Keep up the great work ^^

**Comment by SophrosyneCapital** [comment]
I third this request

**Comment by mkufel** [comment]
+1

**Comment by dronzxc** [comment]
Any updates regarding Order books via WS API? I need it for algo trading.

**Comment by Yoruichi** [comment]
The WS API just provide a part of ORDER BOOK data. So we disabled it. 
We're working on providing a REST api for Kline data. I hope it will be useful
