### ISSUE TITLE
24hr Ticker - Missing Data & Null Fields

### ISSUE THREAD

**Issue by francesco-adamo** [Bitrue-exchange/bitrue-official-api-docs#20]
Hi, I have noticed that when asking for the 24hr ticker data, there are a few issues.

1) Missing Data
When requesting full data, it appears that some symbols are missing in the response for no reason and without an apparent pattern.

As an example:
REQUEST: `GET https://openapi.bitrue.com/api/v1/ticker/24hr`

In my tests one time BTRUSDT was missing missing, but the very next time it was there.

2) Many fields are `null`.
This is not the expected behavior, as shown in the documentation.

As an example:
REQUEST: `GET https://openapi.bitrue.com/api/v1/ticker/24hr?symbol=BTRUSDT`

In the response, all these fields are `null`:
`priceChangePercent, weightedAvgPrice, prevClosePrice, lastQty, bidPrice, askPrice, openPrice`

**Comment by Yoruichi** [comment]
We'll fix it in the next version. Maybe we can't get data for some fields, so that these fields are in place only.
