### ISSUE TITLE
Add average Price to Query order (USER_DATA)

### ISSUE THREAD

**Issue by neilbirtles** [Bitrue-exchange/bitrue-official-api-docs#3]
Query order (USER_DATA) only provides the price that the order was placed at, it doesnt give you the average fill price for the order and there is no way to get this info from the API - the information is however presented on the website in order history

**Comment by snub-fighter** [comment]
You'll have to bring this up with Bitrue.  I have requested feature enhancements in the past but they are more concerned with their lending platform than they are their trading platform.

**Comment by Yoruichi** [comment]
Will fix it
