### ISSUE TITLE
no Klines/Candlestick api

### ISSUE THREAD

**Issue by rayeaster** [Bitrue-exchange/bitrue-official-api-docs#4]
seems no api doc for following data although the php sdk shows sth:
https://github.com/Bitrue-exchange/bitrue-official-api-docs/blob/master/PHP-sdk.php#L63
```
Kline/Candlestick chart intervals:

m -> minutes; h -> hours; d -> days; w -> weeks; M -> months

1m
5m
15m
30m
1h
1d
1w
1M
```

**Comment by Yoruichi** [comment]
Note this. And we'll provide the web-socket API for this data ASAP
