### ISSUE TITLE
does bitrue support websocket api?

### ISSUE THREAD

**Issue by rayeaster** [Bitrue-exchange/bitrue-official-api-docs#5]

**Comment by Yoruichi** [comment]
Note this. And we'll provide it ASAP.

**Comment by SophrosyneCapital** [comment]
Hello,

I see some info on a websocket API, but I don't see any market data streams.
Will these be added?

**Comment by camposfyi** [comment]
Any info on the websockets api? seems like it was implemented, but the documentation is horrible. is there a websocket api? and if so, where are the docs?

**Comment by lathanbritz** [comment]
also looking for public market trade data websocket streams
